### PR TITLE
Adding support for TypeScript

### PR DESCRIPTION
**Pull request by imCorfitz**
This PR includes types for the latest updated package, and extends rollup to copy the types to the `dist` folder during build. I did however experience a series of updates to the `package-lock.json` file, which I suspect is due to me running a later version of Node.js. 

I am installing Node.js v 14.21.3 now - and wil ltry to install package again hoping it will resolve it.

### CODE REVIEW

**Comment by imCorfitz** [comment]
After installing Node.js v 14.21.3, the package-lock.json file simply got added to, so now it makes more sense. Should be ready for merge.

**Review by AllanOricil — APPROVED** [review]

**Comment by AllanOricil** [comment]
@imCorfitz add these two secrets in ur github repository.

image

image

The integration tests run on the context of ur repository, and since secrets aren't shared between repositories, ur jobs are running with empty env vars:

image

I will approve changes now because I tested and it works

**Comment by imCorfitz** [comment]
Great - I performed a local test and everything also worked. (Used Photoshop to replace my credentials).

Screenshot-2023-02-25-at-15 20 31

I have added the secrets for future updates. Cheers.

**Comment by AllanOricil** [comment]
ts types were packaged. Thank you @imCorfitz 
image

**Pull request merged**
